# Generated by Django 3.1.4 on 2021-12-10 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0002_expenditure_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenditure',
            name='timestamp',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
