# Generated by Django 3.1.4 on 2021-12-10 09:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0005_auto_20211210_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenditure',
            name='timestamp',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
