# Generated by Django 3.1.4 on 2021-12-10 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0006_auto_20211210_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenditure',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
